#!/bin/bash

export BAIDS_HOME="${HOME}/.baids"
export BAIDS="${BAIDS_HOME}/baids"
export BAIDS_FUNCS_DIR="${BAIDS_HOME}/functions.d"
export BAIDS_ALIAS_DIR="${BAIDS_HOME}/aliases.d"
export GIT_REPO="https://github.com/rcmorano/baids.git"

INSTALL=$1
if [ "$INSTALL" == "install" ]
then
    BASH_RC="${HOME}/.bashrc"
    git clone $GIT_REPO $BAIDS_HOME
    grep -q "$BAIDS" $BASH_RC || echo ". $BAIDS" >> $BASH_RC
    echo -e "\n[+] 'baids' is now installed!"
    echo -e "[-] Now please, load 'baids' executing:\n"
    echo "    source $BAIDS"
    exit 0
fi

for file in ${BAIDS_FUNCS_DIR}/* ${BAIDS_ALIAS_DIR}/*
do
    source $file
done
