#!/bin/bash

export DBAIDS_HOME="${HOME}/.docker-baids"
export DBAIDS="${DBAIDS_HOME}/docker-baids"
export DBAIDS_FUNCS_DIR="${DBAIDS_HOME}/functions.d"
export DBAIDS_ALIAS_DIR="${DBAIDS_HOME}/aliases.d"
export GIT_REPO="https://github.com/rcmorano/docker-baids.git"

INSTALL=$1
if [ "$INSTALL" == "install" ]
then
    BASH_RC="${HOME}/.bashrc"
    git clone $GIT_REPO $DBAIDS_HOME
    grep -q "$DBAIDS" $BASH_RC || echo ". $DBAIDS" >> $BASH_RC
    echo -e "\n[+] 'docker-baids' is now installed!"
    echo -e "[-] Now please, load 'docker-baids' executing:\n"
    echo "    source $DBAIDS"
    exit 0
fi

for file in ${DBAIDS_FUNCS_DIR}/* ${DBAIDS_ALIAS_DIR}/*
do
    source $file
done
